---
- hosts: localhost
  vars:
    token: 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
    branch: main
    github_user: AlexyIbrahim
    repo_name: Notifications
  tasks:
    - name: Check if bump2version is installed
      command: pip show bump2version
      register: bump2version_installed
      ignore_errors: yes

    - name: Install bump2version
      command: pip install bump2version
      when: bump2version_installed.rc != 0

    - name: Increment the patch version
      command: bump2version --allow-dirty --list patch # allow uncommitted changes
      register: bump2version_output

    - name: Extract the new version
      set_fact:
        version: "{{ bump2version_output.stdout_lines | select('match', '^new_version=.*') | map('replace', 'new_version=', '') | first }}"

    - name: Log version
      debug:
        var: version

    - name: Build the package
      command: poetry build

    - name: Publish the package
      command: poetry publish

#    - name: Create a new GitHub release
#      uri:
#        url: https://api.github.com/repos/{{ github_user }}/{{ repo_name }}/releases
#        method: POST
#        headers:
#          Authorization: "token {{ token }}"
#        body_format: json
#        body:
#          tag_name: "{{ version }}"
#          target_commitish: "{{ branch }}"
#          name: "{{ version }}"
#          body: "Release of version {{ version }}"
#          draft: false
#          prerelease: false
#        status_code: 201
#        validate_certs: False
#      when: token is defined and token != ''

    - name: Comment out .gitignore entries
      replace:
        path: .gitignore
        regexp: '^(.*)$'
        replace: '#\1'

    - name: Add all files
      command: git add --all

    - name: Commit changes
      command: git commit -m "Commit all files"

    - name: Push changes
      command: git push origin develop

    - name: Uncomment .gitignore entries
      replace:
        path: .gitignore
        regexp: '^#(.*)$'
        replace: '\1'