---
- hosts: localhost
  tasks:
    - name: Check if bump2version is installed
      command: pip show bump2version
      register: bump2version_installed
      ignore_errors: yes

    - name: Install bump2version
      command: pip install bump2version
      when: bump2version_installed.rc != 0

    - name: Increment the patch version
      command: bump2version --allow-dirty patch # allow uncommitted changes

    - name: Build the package
      command: poetry build

    - name: Publish the package
      command: poetry publish